spring.datasource.url=jdbc:postgresql://db.vlxifaqppbwnuhgnnxhr.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Pelaofabrizzio
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

